#!/bin/bash

if [[ ! -d "vcpkg" ]]; then
	git clone https://github.com/microsoft/vcpkg
fi
./vcpkg/bootstrap-vcpkg.bat
./vcpkg/vcpkg install pkgconf
./vcpkg/vcpkg install gmp --triplet=x64-windows
./vcpkg/vcpkg integrate install
